import type { Metadata } from "next";
import "./globals.css";
import "@/assets/css/montserrat-alternates.css"
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Inner Garden",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main className="bg-primary">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
