export { default as logo } from "./logo.svg";
export { default as banner1 } from "./banner1.jpg";
export { default as banner2 } from "./banner2.jpg";
export { default as banner3 } from "./banner3.jpg";
export { default as icon1 } from "./icon1.svg";
export { default as icon2 } from "./icon2.svg";
export { default as icon3 } from "./icon3.svg";
export { default as icon5 } from "./icon5.svg";
export { default as icon6 } from "./icon6.svg";
export { default as icon7 } from "./icon7.svg";
export { default as profile } from "./profile.png";
export { default as profile2 } from "./profile2.png";
export { default as banner4 } from "./banner4.jpg";
export { default as banner5 } from "./banner5.jpg";
export { default as banner6 } from "./banner6.png";
export { default as banner7 } from "./banner7.jpg";
export { default as banner8 } from "./banner8.png";
export { default as banner9 } from "./banner9.png";
export { default as banner10 } from "./banner10.png";
export { default as explore } from "./explore.svg";
export { default as plus } from "./plus.svg";
export { default as img1 } from "./img1.png";
export { default as img2 } from "./img2.png";
export { default as upload } from "./upload.svg";
export { default as img3 } from "./img3.svg";
export { default as footer1 } from "./footer1.svg";
export { default as inner } from "./inner.svg";
export { default as play } from "./play.png";
export { default as home_banner_1 } from "./home_banner_1.jpg";
export { default as home_banner_2 } from "./home_banner_2.jpg";
export { default as home_banner_3 } from "./home_banner_3.jpg";
export { default as home_banner_4 } from "./home_banner_4.jpg";
export { default as home_banner_5 } from "./home2.jpg";
export { default as home_banner_6 } from "./home4.jpg";
export { default as blogCard4Img } from "./blogCard4Img.png";
export { default as articleBg } from "./articleBg.png";
export { default as policeBg } from "./policiesBg.svg";
export { default as butterfly } from "./buttterfly.svg";
export { default as edit } from "./edit.png";
export { default as insect } from "./insect.svg";
export { default as union } from "./Union.svg";
export { default as blogCardImg } from "./blogCard5img.png";
export { default as img11 } from "./img1.png";
export { default as donate } from "./donateBg.png";
export { default as contactBg } from "./contactBg.png";
export { default as linkedin } from "./LinkedIn.png";
export { default as profileBg } from "./Profile_Public_Bg.png";
export { default as acadmeyBg } from "./acdameyBG.png";
export { default as ellipse1 } from "./Ellipse 1.svg";
export { default as ellipse2 } from "./Ellipse 2.svg";
export { default as ellipse3 } from "./Ellipse 3.svg";
export { default as ellipse4 } from "./Ellipse 4.svg";
export { default as ellipse5 } from "./Ellipse 5.svg";
export { default as bud } from "./bud 1.png";
export { default as strom } from "./storm 1.png";
export { default as raking } from "./raking 1.png";
export { default as gardening } from "./gardening 1.png";
export { default as brain2 } from "./brain2.png";
export { default as brain3 } from "./brain3.png";
export { default as sun } from "./sunny.png";
export { default as cloud } from "./cloud.png";
export { default as rain } from "./rainy.png";
export { default as storm } from "./storm 1.png";
export { default as miss } from "./misss.png";
export { default as gandhi } from "./gandhi.png";
export { default as cognition } from "./cognition.svg";
export { default as left } from "./chevron-left.svg";
export { default as right } from "./chevron-right.svg";
export { default as profile3 } from "./profile3.svg";
export { default as nelson } from "./nelson.svg";
export { default as billgats } from "./billgats.svg";
export { default as trailsImg } from "./trailsImg.png";
export { default as headerButterfly } from "./headerButterfly.svg";
export { default as searchLogo } from "./searchImg.png";
export { default as innerVedio } from "./innerVedio.png";
export { default as joinUs } from "./joinUsImg.png";
export { default as martin } from "./martin-valerie 2.png";
export { default as wellPop } from "./wellPop.png";
export { default as wellorithm } from "./g12.svg";
export { default as cloudy } from "./cloudy.png";
export { default as brainn } from "./cognition (1).svg";
export { default as coverImageProfile } from "./Frame 1000001795.svg";
export { default as ImageProfile } from "./Group 1000001794.svg";
export { default as CoverImageProfilePage } from "./CoverImageProfilePage.svg";
